name: Tests

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - '3.*'
    paths:
    - 'Tools/msi/**'
  pull_request:
    branches:
    - 'main'
    - '3.*'
    paths:
    - 'Tools/msi/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_win32:
    name: 'Windows (x86) Installer'
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython installer
      run: .\Tools\msi\build.bat -x86

  build_win_amd64:
    name: 'Windows (x64) Installer'
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython installer
      run: .\Tools\msi\buildrelease.bat -x64
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          PCbuild/amd64/
